@base=https://api1.qcwxkjvip.com/qcwx/

### get token

GET {{base}}token/getToken?key=qcwx_android


### get watchface list
@hardwareVersion=M311A_v1.0
@token=15ef6eb5403406c1da0dc4a4defa2ea1
GET {{base}}device-file/list-watch-face?hardwareVersion={{hardwareVersion}}
token: {{token}}