name: qcwxservice
description: Interface with JL backend.
version: 1.0.1

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  dio: ^5.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
